---
version: 2
models:
- name: "model_sanity_working_pipeline_shared_db_1_Limit_2"
  tags:
  - "prophecy_temp"
- name: "model_sanity_working_pipeline_shared_db_1_Union_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_sanity_working_pipeline_shared_db_1_source"
  database: "hive_metastore"
  schema: "qa_db_warehouse"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_sanity_working_pipeline_shared_db_1_post_Limit_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_working_pipeline_shared_db_1_post_Union_1_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_working_pipeline_shared_db_1_pre_Reformat_4_0"
    tags:
    - "prophecy_temp"
