---
version: 2
models:
- name: "model_sanity_shared_pipeline_1_DataCleansing_1"
  tags:
  - "prophecy_temp"
- name: "model_sanity_shared_pipeline_1_DynamicSelect_1"
  tags:
  - "prophecy_temp"
- name: "model_sanity_shared_pipeline_1_Join_1"
  tags:
  - "prophecy_temp"
- name: "model_sanity_shared_pipeline_1_Limit_2"
  tags:
  - "prophecy_temp"
- name: "model_sanity_shared_pipeline_1_filter_by_count"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_sanity_shared_pipeline_1_source"
  database: "hive_metastore"
  schema: "qa_db_warehouse"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_sanity_shared_pipeline_1_post_Limit_2_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_shared_pipeline_1_post_filter_by_count_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_shared_pipeline_1_pre_filter_by_count_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_shared_pipeline_1_pre_filter_by_count_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_shared_pipeline_1_pre_filter_by_count_2"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_shared_pipeline_1_pre_filter_by_count_3"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_sanity_shared_pipeline_1_pre_filter_by_count_4"
    tags:
    - "prophecy_temp"
